# Generated by Django 6.0.4 on 2026-04-19 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compradores', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('selecionado', 'Veículo Selecionado'), ('reservado', 'Veículo Reservado'), ('pagamento_pendente', 'Pagamento Pendente'), ('pago', 'Pago'), ('concluido', 'Concluído (Veículo Retirado)'), ('cancelado', 'Cancelado')], default='selecionado', max_length=30)),
                ('codigo_pagamento', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('data_selecao', models.DateTimeField(auto_now_add=True)),
                ('data_reserva', models.DateTimeField(blank=True, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('reserva_expira_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compradores.comprador')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Histórico de Venda',
                'verbose_name_plural': 'Históricos de Vendas',
                'ordering': ['criado_em'],
            },
        ),
    ]
