# Generated by Django 6.0.4 on 2026-04-19 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('quilometragem', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['preco'],
            },
        ),
    ]
