# Generated by Django 6.0.4 on 2026-04-19 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf_hash', models.CharField(help_text='Hash SHA-256 do CPF', max_length=64, unique=True)),
                ('cpf_masked', models.CharField(help_text='CPF mascarado: ***.***.***-XX', max_length=14)),
                ('rg_hash', models.CharField(help_text='Hash SHA-256 do RG', max_length=64, unique=True)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'ordering': ['nome'],
            },
        ),
    ]
